name: Release Linux Artifacts

on:
  push:
    tags:
      - 'v*'

jobs:
  release-linux-artifacts:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code and LFS files
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Install dependencies
        run: npm ci

      - name: Build Linux distributables
        run: npm run dist:linux

      - name: Zip linux-unpacked
        run: |
          cd dist
          zip -r excalidraw-linux64.zip linux-unpacked

      - name: Upload Release Assets
        uses: softprops/action-gh-release@v2
        with:
          files: |
            dist/Excalidraw-1.0.0.AppImage
            dist/excalidraw_1.0.0_amd64.deb
            dist/excalidraw-linux64.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
